// #if UNITY_EDITOR
// using System;
// using System.IO;
// using System.Linq;
// using System.Text;
// using Script.GameInfo.Base;
// using UnityEditor;
// using UnityEditor.Compilation;
//
// namespace Script.GameInfo.Table.Editor {
//     [InitializeOnLoad]
//     public static class GameInfoManagerCodeGen {
//         private const string OutputPath = "Assets/GAME_INFO_TABLE/Scripts/GameInfoManager.AddressableKeys.g.cs";
//
//         static GameInfoManagerCodeGen() {
//             CompilationPipeline.compilationFinished += OnCompilationFinished;
//         }
//
//         private static void OnCompilationFinished(object _) {
//             Generate();
//         }
//
//         [MenuItem("Tools/GameInfo/Generate Addressable Keys")]
//         public static void Generate() {
//             var types = TypeCache.GetTypesDerivedFrom<TableBase>()
//                                  .Where(t => !t.IsAbstract && !t.IsGenericType)
//                                  .Select(t => t.Name)
//                                  .Distinct(StringComparer.Ordinal)
//                                  .OrderBy(x => x, StringComparer.Ordinal)
//                                  .ToArray();
//
//             var sb = new StringBuilder();
//             sb.AppendLine("// <auto-generated />");
//             sb.AppendLine("namespace Script.GameInfo.Table {");
//             sb.AppendLine("    public partial class GameInfoManager : IGameInfoManager {");
//             sb.AppendLine("        public static readonly string[] AddressableKeys = new string[] {");
//             foreach (var typeName in types) {
//                 sb.AppendLine($"            \"{typeName}\",");
//             }
//
//             sb.AppendLine("        };");
//             sb.AppendLine("    }");
//             sb.AppendLine("}");
//
//             var dir = Path.GetDirectoryName(OutputPath);
//             if (!Directory.Exists(dir))
//                 Directory.CreateDirectory(dir!);
//
//             File.WriteAllText(OutputPath, sb.ToString(), Encoding.UTF8);
//             AssetDatabase.Refresh();
//         }
//     }
// }
// #endif