#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using System.Text;
using Script.GameInfo.Base;
using UnityEditor;

namespace Script.GameInfo.Table.Editor {
    public class GameInfoManagerCodeGen : AssetPostprocessor {
        private const string OutputPath = "Assets/GAME_INFO_TABLE/Script/GameInfoManager.AddressableKeys.g.cs";
        private const string WatchRoot  = "Assets/GAME_INFO_TABLE/Script/";

        private static bool _pendingGenerate;

        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths
        ) {
            if (!HasRelevantScriptChange(importedAssets) && !HasRelevantScriptChange(deletedAssets) && !HasRelevantScriptChange(movedAssets) && !HasRelevantScriptChange(movedFromAssetPaths)) {
                return;
            }

            if (OnlyGeneratedFileChanged(importedAssets, deletedAssets, movedAssets, movedFromAssetPaths))
                return;

            RequestGenerate();
        }

        private static bool HasRelevantScriptChange(string[] paths) {
            if (paths == null || paths.Length == 0)
                return false;

            foreach (var path in paths) {
                if (string.IsNullOrEmpty(path))
                    continue;

                if (!path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
                    continue;

                if (!path.StartsWith(WatchRoot, StringComparison.OrdinalIgnoreCase))
                    continue;

                if (string.Equals(path, OutputPath, StringComparison.OrdinalIgnoreCase))
                    continue;

                return true;
            }

            return false;
        }

        private static bool OnlyGeneratedFileChanged(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths
        ) {
            return IsOnlyGeneratedFile(importedAssets)
                && IsOnlyGeneratedFile(deletedAssets)
                && IsOnlyGeneratedFile(movedAssets)
                && IsOnlyGeneratedFile(movedFromAssetPaths);
        }

        private static bool IsOnlyGeneratedFile(string[] paths) {
            if (paths == null || paths.Length == 0)
                return true;

            foreach (var path in paths) {
                if (string.IsNullOrEmpty(path))
                    continue;

                if (!string.Equals(path, OutputPath, StringComparison.OrdinalIgnoreCase))
                    return false;
            }

            return true;
        }

        private static void RequestGenerate() {
            if (_pendingGenerate)
                return;

            _pendingGenerate            =  true;
            EditorApplication.delayCall += DelayedGenerate;
        }

        private static void DelayedGenerate() {
            _pendingGenerate = false;
            Generate();
        }

        private static void Generate() {
            var types = TypeCache.GetTypesDerivedFrom<TableBase>()
                                 .Where(t => t != null && !t.IsAbstract && !t.IsGenericType)
                                 .Select(t => t.Name)
                                 .Distinct(StringComparer.Ordinal)
                                 .OrderBy(x => x, StringComparer.Ordinal)
                                 .ToArray();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using Script.GameInfo.Table.Interface;");
            sb.AppendLine("namespace Script.GameInfo.Table {");
            sb.AppendLine("    public partial class GameInfoManager {");
            sb.AppendLine("        public static readonly string[] AddressableKeys = new string[] {");
            foreach (var typeName in types) {
                sb.AppendLine($"            \"{typeName}\",");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var newCode = sb.ToString();

            var dir = Path.GetDirectoryName(OutputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            if (File.Exists(OutputPath)) {
                var oldCode = File.ReadAllText(OutputPath);
                if (string.Equals(oldCode, newCode, StringComparison.Ordinal))
                    return;
            }

            File.WriteAllText(OutputPath, newCode, new UTF8Encoding(false));
            AssetDatabase.ImportAsset(OutputPath, ImportAssetOptions.ForceUpdate);
        }
    }
}
#endif