// <auto-generated>
// This file is generated by TriggerFactoryCodeGenerator.
// Do not edit manually.
// </auto-generated>

namespace Script.GamePlay.Stage {
    public static partial class TriggerFactory {
        private static global::Script.GamePlay.Stage.ClientTriggerBase CreateInternal(global::Script.GameInfo.Dungeon.TriggerBase trigger) {
            return trigger switch {
                global::Script.GameInfo.Dungeon.PlayerDieTrigger typed => new global::Script.GamePlay.Stage.ClientPlayerDieTrigger(typed),
                _ => null,
            };
        }
    }
}
