#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Script.GameInfo.Dungeon;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;

namespace Script.GamePlay.Stage.Editor {
    [InitializeOnLoad]
    public static class ActionFactoryCodeGenerator {
        private const string OutputPath = "Assets/Script/GamePlay/Stage/Action/Generator/ActionFactory.CodeGen.cs";

        static ActionFactoryCodeGenerator() {
            CompilationPipeline.compilationFinished -= OnCompilationFinished;
            CompilationPipeline.compilationFinished += OnCompilationFinished;

            EditorApplication.delayCall += Generate;
        }

        [MenuItem("Generator/Generate ActionFactory")]
        public static void GenerateMenu() {
            Generate();
        }

        private static void OnCompilationFinished(object _) {
            Generate();
        }

        private static void Generate() {
            var actionTypes = TypeCache.GetTypesDerivedFrom<ActionBase>()
                .Where(IsConcreteType)
                .OrderBy(t => t.FullName)
                .ToArray();

            var clientActionTypes = TypeCache.GetTypesDerivedFrom<ClientActionBase>()
                .Where(IsConcreteType)
                .OrderBy(t => t.FullName)
                .ToArray();

            var clientGroups = clientActionTypes
                .GroupBy(t => t.Name)
                .ToDictionary(g => g.Key, g => g.ToArray());

            var pairs = new List<(Type actionType, Type clientType)>();
            var warnings = new List<string>();

            foreach (var actionType in actionTypes) {
                var expectedClientName = "Client" + actionType.Name;

                if (!clientGroups.TryGetValue(expectedClientName, out var matchedClients))
                    continue;

                if (matchedClients.Length > 1) {
                    warnings.Add(
                        $"[ActionFactoryCodeGen] '{expectedClientName}' 타입이 여러 개입니다. " +
                        $"'{actionType.FullName}' 매칭은 스킵합니다.");
                    continue;
                }

                var clientType = matchedClients[0];

                var ctor = clientType.GetConstructor(
                    BindingFlags.Public | BindingFlags.Instance,
                    binder: null,
                    types: new[] { actionType },
                    modifiers: null
                );

                if (ctor == null) {
                    warnings.Add(
                        $"[ActionFactoryCodeGen] '{clientType.FullName}' 에 " +
                        $"생성자 .ctor({actionType.Name}) 가 없습니다. 스킵합니다.");
                    continue;
                }

                pairs.Add((actionType, clientType));
            }

            var source = BuildSource(pairs);

            var directory = Path.GetDirectoryName(OutputPath);
            if (string.IsNullOrWhiteSpace(directory) == false && Directory.Exists(directory) == false) {
                Directory.CreateDirectory(directory);
            }

            var shouldWrite = File.Exists(OutputPath) == false || File.ReadAllText(OutputPath) != source;
            if (shouldWrite) {
                File.WriteAllText(OutputPath, source, new UTF8Encoding(false));
                AssetDatabase.Refresh();
                Debug.Log($"[ActionFactoryCodeGen] Generated: {OutputPath}");
            }

            foreach (var warning in warnings) {
                Debug.LogWarning(warning);
            }
        }

        private static bool IsConcreteType(Type type) {
            return type != null
                   && type.IsClass
                   && type.IsAbstract == false
                   && type.IsGenericType == false
                   && type.IsGenericTypeDefinition == false;
        }

        private static string BuildSource(IReadOnlyList<(Type actionType, Type clientType)> pairs) {
            var sb = new StringBuilder(4096);

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated by ActionFactoryCodeGenerator.");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();

            sb.AppendLine("namespace Script.GamePlay.Stage {");
            sb.AppendLine("    public static partial class ActionFactory {");
            sb.AppendLine("        private static global::Script.GamePlay.Stage.ClientActionBase CreateInternal(global::Script.GameInfo.Dungeon.ActionBase action) {");
            sb.AppendLine("            return action switch {");

            if (pairs.Count > 0) {
                foreach (var (actionType, clientType) in pairs) {
                    sb.Append("                ");
                    sb.Append(GetGlobalTypeName(actionType));
                    sb.Append(" typed => new ");
                    sb.Append(GetGlobalTypeName(clientType));
                    sb.Append("(typed),");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("                _ => null,");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string GetGlobalTypeName(Type type) {
            var fullName = type.FullName ?? type.Name;
            return "global::" + fullName.Replace("+", ".");
        }
    }
}
#endif